name: Publish Release

on: push

jobs:
  build-and-publish:
    name: Build and publish to TestPyPI and PyPI
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Poetry
      run: |
        pipx install poetry==1.3.1
        poetry self add "poetry-dynamic-versioning[plugin]"

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'

    - name: Install dependencies
      run: poetry install

    - name: Build distribution
      run: poetry build

    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish distribution 📦 to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
