name: Test Pull Request

on:
  pull_request:
    branches:
    - master

jobs:
  run_test_suite:
    name: Test HeatmapX
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 2
      matrix:
        python-version:
          - '3.9'
          - '3.10'

    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry==1.3.1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --with test

      - name: Test with pytest
        run: poetry run python -m pytest
